<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reclamation extends \App\Entity\Reclamation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Date_Rec' => [parent::class, 'Date_Rec', null],
        "\0".parent::class."\0".'Description_Rec' => [parent::class, 'Description_Rec', null],
        "\0".parent::class."\0".'ID_Article' => [parent::class, 'ID_Article', null],
        "\0".parent::class."\0".'ID_Utilisateur' => [parent::class, 'ID_Utilisateur', null],
        "\0".parent::class."\0".'Images_Reclamation1' => [parent::class, 'Images_Reclamation1', null],
        "\0".parent::class."\0".'Images_Reclamation2' => [parent::class, 'Images_Reclamation2', null],
        "\0".parent::class."\0".'Stat_Rec' => [parent::class, 'Stat_Rec', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'reponses' => [parent::class, 'reponses', null],
        'Date_Rec' => [parent::class, 'Date_Rec', null],
        'Description_Rec' => [parent::class, 'Description_Rec', null],
        'ID_Article' => [parent::class, 'ID_Article', null],
        'ID_Utilisateur' => [parent::class, 'ID_Utilisateur', null],
        'Images_Reclamation1' => [parent::class, 'Images_Reclamation1', null],
        'Images_Reclamation2' => [parent::class, 'Images_Reclamation2', null],
        'Stat_Rec' => [parent::class, 'Stat_Rec', null],
        'id' => [parent::class, 'id', null],
        'reponses' => [parent::class, 'reponses', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
