<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avantages' => [parent::class, 'avantages', null],
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null],
        "\0".parent::class."\0".'descriptionprod' => [parent::class, 'descriptionprod', null],
        "\0".parent::class."\0".'evaluations' => [parent::class, 'evaluations', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image_large' => [parent::class, 'image_large', null],
        "\0".parent::class."\0".'image_small1' => [parent::class, 'image_small1', null],
        "\0".parent::class."\0".'image_small2' => [parent::class, 'image_small2', null],
        "\0".parent::class."\0".'image_small3' => [parent::class, 'image_small3', null],
        "\0".parent::class."\0".'nombreProduitsEnStock' => [parent::class, 'nombreProduitsEnStock', null],
        "\0".parent::class."\0".'nomprod' => [parent::class, 'nomprod', null],
        "\0".parent::class."\0".'prixprod' => [parent::class, 'prixprod', null],
        "\0".parent::class."\0".'sizeprod' => [parent::class, 'sizeprod', null],
        'avantages' => [parent::class, 'avantages', null],
        'categorie' => [parent::class, 'categorie', null],
        'descriptionprod' => [parent::class, 'descriptionprod', null],
        'evaluations' => [parent::class, 'evaluations', null],
        'id' => [parent::class, 'id', null],
        'image_large' => [parent::class, 'image_large', null],
        'image_small1' => [parent::class, 'image_small1', null],
        'image_small2' => [parent::class, 'image_small2', null],
        'image_small3' => [parent::class, 'image_small3', null],
        'nombreProduitsEnStock' => [parent::class, 'nombreProduitsEnStock', null],
        'nomprod' => [parent::class, 'nomprod', null],
        'prixprod' => [parent::class, 'prixprod', null],
        'sizeprod' => [parent::class, 'sizeprod', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
