<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \App\Entity\Message implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null],
        "\0".parent::class."\0".'datemsg' => [parent::class, 'datemsg', null],
        "\0".parent::class."\0".'descriptionmsg' => [parent::class, 'descriptionmsg', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'replies' => [parent::class, 'replies', null],
        "\0".parent::class."\0".'titremsg' => [parent::class, 'titremsg', null],
        'contenu' => [parent::class, 'contenu', null],
        'datemsg' => [parent::class, 'datemsg', null],
        'descriptionmsg' => [parent::class, 'descriptionmsg', null],
        'id' => [parent::class, 'id', null],
        'replies' => [parent::class, 'replies', null],
        'titremsg' => [parent::class, 'titremsg', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
