<?php

namespace ContainerB2CBQbC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1gX3nGDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1gX3nGD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1gX3nGD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evaluation' => ['privates', '.errored..service_locator.1gX3nGD.App\\Entity\\Evaluation', NULL, 'Cannot autowire service ".service_locator.1gX3nGD": it needs an instance of "App\\Entity\\Evaluation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'evaluation' => 'App\\Entity\\Evaluation',
        ]);
    }
}
