<?php

namespace ContainerB2CBQbC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MsQa3JSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.msQa3JS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.msQa3JS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentaireForm' => ['privates', 'App\\Form\\Commentaire1Type', 'getCommentaire1TypeService', true],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'commentaireForm' => 'App\\Form\\Commentaire1Type',
            'eventRepository' => 'App\\Repository\\EventRepository',
        ]);
    }
}
