<?php

namespace ContainerB2CBQbC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponses2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.k8aaRc2.App\Entity\Reponses' shared service.
     *
     * @return \App\Entity\Reponses
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.k8aaRc2": it needs an instance of "App\\Entity\\Reponses" but this type has been excluded in "config/services.yaml".');
    }
}
