<?php

namespace ContainerB2CBQbC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReply2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9Sky7qD.App\Entity\Reply' shared service.
     *
     * @return \App\Entity\Reply
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9Sky7qD": it needs an instance of "App\\Entity\\Reply" but this type has been excluded in "config/services.yaml".');
    }
}
